clc;clear;
rVec = [-0.6 -1 0.75];
vVec = [0.8 -0.45 0.45];
mu = 1;
[hVec, eVec, hDote, p, a, nu] = positionVelocity(rVec, vVec, mu);
fprintf('The specific angular momentum vector is: ');
fprintf('%g, %g, %g\n',hVec(1),hVec(2),hVec(3));
fprintf('The eccentricity vector is: ');
fprintf('%g, %g, %g\n',eVec(1),eVec(2),eVec(3));
fprintf('h in I dotted with the eccentricity vector = %g\n',hDote);
fprintf('p = %g km\n',p);
fprintf('a = %g km\n',a);
fprintf('true anomaly = %g rad\n',nu);